---
title: "Participacion politica post proceso constituyente"
format: html
editor: visual
bibliography: Participacion politica post proceso constituyente.bib
link-citations: true
---

## Introcucción 

Chile ha sido desde sus inicios un país que ha contenido un historial político con mucha tensión y conflictos, pasando por muchos procesos de cambio los cuales han tenido diferentes consecuencias para la población chilena debido a la naturaleza polarizada de esta, como también grandes diferencias socioeconómicas e ideologías políticas contradictorias; tal como se puede ver en este estudio del 2019 con intencion presentar un antecedente \"Si bien la búsqueda de consensos ha caracterizado al Chile post Pinochet, finalizando la segunda década del presente siglo, comentarios y análisis consistentes con una mayor polarización han puesto en duda su real alcance en el tiempo.\" (@lindh_fragilidad_2019) Estas condiciones han producido que independiente a quien este gobernando, se genere un descontento en cierta parte de la población; y esta situación a medida que ha pasado el tiempo ha aumentado, teniendo diferentes consecuencias, las cuales se pretenden estudiar en esta investigación, centrando la atención en la situación actual que está viviendo el país postproceso constituyente como podemos ver en \"Más allá del bloqueo provocado por la pandemia de la covid-19 y de los nuevos planes de control sobre la población vinculados a ella, surgieron en América Latina una serie de protestas que dieron un nuevo impulso a los movimientos sociales de izquierda. Pero al mismo tiempo aparecieron en la región grupos de extrema derecha que plantearon una defensa visceral y violenta del capitalismo.\" @barria-asenjo_intersectionalities_2023 , el cual se sitúa en el contexto de un presidente que cuenta con el mayor porcentaje de desapruebo en la historia de chile; como también en un escenario mundial muy agitado por las diferentes confrontaciones que se están dando. Entonces para entender este fenómeno que se está dando nos preguntamos: ¿Cuánto ha afectado el proceso constitucional vivido en chile en los últimos años a la población chilena en cuanto a su participación en nuevas propuestas políticas? Para responder esta pregunta se buscará realizar un análisis de los porcentajes de participación política en todos los procesos constitucionales realizados en el último tiempo, también de años anteriores para realizar comparaciones; así como también se realizará una recolección de datos sobre el grado de confianza o motivación que hay en la población chile para participar en la política aludiendo a temas de cuanto siente que sus opiniones son escuchadas, respetadas, etc. Como lo expresa el estudio realizado en Colombia \" Todo esto para analizar y esclarecer la mejor manera de abordar este fenómeno y escenario, para una mayor eficiencia al solucionar los problemas que nos han llevado a esta situación y así poder avanzar como sociedad consciente para dirigir el país de manera que la gente se quiera involucrar y sienta que su opinión tiene peso en cómo se desarrolla su vida, promoviendo así la democracia \"se ha dudado de que la igualdad dejuicio político existiese realmente y de que, caso de existir, su uso generalizado fuera conveniente.\" (@del_aguila_participacion_1996) . Debido a la complejidad que presenta este último punto se utilizara un modelo utilizado en Colombia que relaciona la con confianza en instituciones y los individuos de la zona de estudio, relacionando la denuncia de crímenes a los crímenes e injusticias realizadas por instituciones \"Para el grupo de variables inherentes a la confianza institucional, la hipótesis describe una relación directa entre la confianza que se tenga en las instituciones y la probabilidad de denunciar, explicada por el hecho de que la antipatía institucional actuaría como una restricción de la denuncia. Los datos que se tienen a disposición respaldan esa idea teniendo en cuenta los bajos niveles de denuncia registrados.\". (@sarria_agudelo_confianza_2023)  .
